version = 13
name = "ecp-page-tag"
description = "Get to know the Fastly Compute@Edge environment with a basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
authors = ["skiel+wafdemo@fastly.com"]
language = "rust"
service_id = "6ICRzT1nWQPNRZjpt2f3Ft"
